title: 软件安装记录
author: Yunyusha
email: 576462286@qq.com
description: > # this means to ignore newlines until "baseurl:"
解决Pycharm打汉字时,提示框不跟随问题

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme:to minima
